services:

    database:
        image: postgres
        volumes:
            - ./database:/database
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        expose:
            - 5432

    backend:
        build: ./backend
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        volumes:
            - ./backend:/backend
        depends_on:
            - database
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    frontend:
        build: ./frontend
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/frontend